nginx_loadbalancer:
    build: nginx_loadbalancer
    ports:
        - "8080:80"
    links:
        - web1
        - web2

web1:
    build: web1

web2:
    build: web2

mysql_perconna:
    image: percona:latest
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=${PASSWORD}
